// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PPCRental.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class UC003_ViewDetailProjectFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "UC003_ViewDetailProject.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "UC003_ViewDetailProject", "\tAs a potential customer\r\n\tI want to see the details of a project\r\n\tSo that I can" +
                    " better decide to buy it.", ProgrammingLanguage.CSharp, new string[] {
                        "web"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "UC003_ViewDetailProject")))
            {
                global::PPCRental.AcceptanceTests.Features.UC003_ViewDetailProjectFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 9
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Avatar",
                        "Images",
                        "PropertyType",
                        "Content",
                        "Street",
                        "Ward",
                        "District",
                        "Price",
                        "UnitPrice",
                        "Area",
                        "Bedroom",
                        "Bathroom",
                        "PackingPlace",
                        "User",
                        "Status",
                        "Note",
                        "Sale"});
            table1.AddRow(new string[] {
                        "ASA LightT",
                        "Asa Light.jpg",
                        "",
                        "Apartment",
                        "NaN",
                        "Bùi Viện",
                        "P.Bến Nghé",
                        "Quận 1",
                        "71000",
                        "USD",
                        "150",
                        "3",
                        "3",
                        "1",
                        "lythihuyenchau@gmail.com",
                        "Đã duyệt",
                        "Done",
                        "Agency"});
            table1.AddRow(new string[] {
                        "CALEDON Tan Phu",
                        "Caledon Tan Phu.jpg",
                        "",
                        "Villa",
                        @"ICON 56 – Modern Style Apartment $ 950 Per Month.Condominium in Rentals 56 Ben Van Don, Ho Chi Minh City, District 4 add to favorites. 22 See all 12 photos.Icon 56 is 4 star building with strategic location and excellent amenities including infinity swimming pool and modern gym. Just walking through Mong bridge (Saigon oldest bridge) or drive through Calmette bridge, you have reached District 1 – the business center of the city",
                        "Bà Lê Chân",
                        "P.Đa Kao",
                        "Quận 1",
                        "55000",
                        "USD",
                        "130",
                        "2",
                        "2",
                        "1",
                        "lythihuyenchau@gmail.com",
                        "Đã duyệt",
                        "Done",
                        "Agency"});
            table1.AddRow(new string[] {
                        "VINH LOC Central",
                        "Vinh Loc Central.jpg",
                        "",
                        "Villa",
                        "Brand new apartments with unbelievable river and city view, completely renovated " +
                            "and tastefully furnished, with attention to details, modern colors, designer lig" +
                            "hting and high quality accessories.",
                        "Đồng Khởi",
                        "P.Cô Giang",
                        "Quận 1",
                        "70000",
                        "USD",
                        "120",
                        "3",
                        "2",
                        "1",
                        "lythihuyenchau@gmail.com",
                        "Đã duyệt",
                        "Done",
                        "Agency"});
            table1.AddRow(new string[] {
                        "SAIGONRESE Plaza",
                        "Saigonrese.jpg",
                        "",
                        "Office",
                        "Very close to the Super Market Co.op Mart Phan Xich Long, 3 min from the Swimming" +
                            " Pool Rach Mieu and also close to the Gym/Yoga on Phan Xich Long Street. 3 min g" +
                            "o to Tan Dinh market or Phu Nhuan market.",
                        "Chu Văn An",
                        "P.Phú Hữu",
                        "Quận 2",
                        "90000",
                        "USD",
                        "200",
                        "3",
                        "3",
                        "1",
                        "lythihuyenchau@gmail.com",
                        "Đã duyệt",
                        "Done",
                        "Agency"});
            table1.AddRow(new string[] {
                        "CAPSULE Residence",
                        "Capsule Residence .jpg",
                        "",
                        "Office",
                        "The well equipped kitchen is opened on a cozy living room and a dining area with " +
                            "table and chairs.. Behind the industrial glass wall you will find the bedroom ar" +
                            "ea with a double bed and a large closet.",
                        "Thảo Điền",
                        "P.An Lợi Đông",
                        "Quận 2",
                        "49500",
                        "USD",
                        "130",
                        "2",
                        "2",
                        "1",
                        "lythihuyenchau@gmail.com",
                        "Đã duyệt",
                        "Done",
                        "Agency"});
            table1.AddRow(new string[] {
                        "FLORAL HOA BINH",
                        "Floral Hoa Binh.jpg",
                        "",
                        "Villa",
                        @"Vinhomes Central Park is a new development that is in the heart of everything that Ho Chi Minh has to offer. Located in Binh Thanh District, it is within easy reach of the new Metro Line No. 1 Ben Thanh – Suoi Tien, 4 minutes to downtown District 1 and 3 minutes to the new Thu Thiem urban area in the near future.",
                        "Nguyễn Tư Nghiêm",
                        "P.An Phú",
                        "Quận 2",
                        "79000",
                        "USD",
                        "180",
                        "4",
                        "4",
                        "1",
                        "lythihuyenchau@gmail.com",
                        "Đã duyệt",
                        "Done",
                        "Agency"});
            table1.AddRow(new string[] {
                        "ORIENT Plaza",
                        "Orient Plaza.jpg",
                        "",
                        "Apartment",
                        @"Located on Nguyen Huu Canh Street, this nice apartment has all amenities like swimming pool, sauna, jacuzzi, gym and pet allowed…It has fully furnished with everything you need like TV, fridge, washing machine, wardrobe, sofa, dining table, kitchenette, …With $1600/month for 3 bedroom apartment. Inclusive of management fee",
                        "Nguyễn Tư Nghiêm",
                        "P.01",
                        "Quận 3",
                        "42200",
                        "USD",
                        "100",
                        "2",
                        "2",
                        "1",
                        "annguyen",
                        "Đã duyệt",
                        "Done",
                        "Agency"});
            table1.AddRow(new string[] {
                        "RIVA Garden",
                        "Riva Garden.jpg",
                        "",
                        "Apartment",
                        @"The Nguyen Dinh Chinh  is a lovely option for the renter seeking home-comfort away from the noise of the city center. Located in Phu Nhuan district, the unit is conveniently accessible to local shops and eateries. This serviced apartment provides space and everything needed for you to feel at home.",
                        "Vườn Chuối",
                        "P.02",
                        "Quận 3",
                        "78400",
                        "USD",
                        "168",
                        "3",
                        "4",
                        "2",
                        "annguyen",
                        "Đã duyệt",
                        "Done",
                        "Agency"});
            table1.AddRow(new string[] {
                        "CITY Gate",
                        "City Gate.jpg",
                        "",
                        "Villa",
                        @"Studio apartment at central of CBD, nearby Ben Thanh market, Bui Vien Backpacker Area, 23/9 park…Live here, and the best and most beloved sites of the city will be just outside your door – from the cafes and restaurants of the financial district, to the waterfront shops and attractions of downtown Ben Thanh. It’s all just steps away.",
                        "Nguyễn Hiền",
                        "P.03",
                        "Quận 3",
                        "120000",
                        "USD",
                        "250",
                        "4",
                        "4",
                        "2",
                        "Thang@gmail.com",
                        "Đã duyệt",
                        "Done",
                        "Agency"});
            table1.AddRow(new string[] {
                        "MY HUNG Prop 3",
                        "My Hung Prop.jpg",
                        "",
                        "Villa",
                        "NaN",
                        "Phú Lâm A",
                        "P.07",
                        "Quận 6",
                        "115000",
                        "USD",
                        "280",
                        "4",
                        "4",
                        "2",
                        "lythihuyenchau@gmail.com",
                        "Đã duyệt",
                        "Done",
                        "Agency"});
            table1.AddRow(new string[] {
                        "NovaLand",
                        "NovaLand.jpg",
                        "NovaLand.jpg",
                        "House",
                        "The well equipped kitchen is opened on a cozy living room and a dining area with " +
                            "table and chairs.. Behind the industrial glass wall you will find the bedroom ar" +
                            "ea with a double bed and a large closet.",
                        "Đặng Dung",
                        "P.Bình Khánh",
                        "Q. Bình Thạnh",
                        "45000",
                        "USD",
                        "240",
                        "2",
                        "2",
                        "2",
                        "annguyen",
                        "Đã duyệt",
                        "Done",
                        "Agency"});
#line 10
testRunner.Given("the following project", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Detail project can be seen")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UC003_ViewDetailProject")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("web")]
        public virtual void DetailProjectCanBeSeen()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Detail project can be seen", ((string[])(null)));
#line 25
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 26
 testRunner.When("I open the details of \'ASA LightT\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Avatar",
                        "Images",
                        "PropertyType",
                        "Content",
                        "Street",
                        "Ward",
                        "District",
                        "Price",
                        "UnitPrice",
                        "Area",
                        "Bedroom",
                        "Bathroom",
                        "PackingPlace",
                        "User",
                        "Status",
                        "Note",
                        "Sale"});
            table2.AddRow(new string[] {
                        "ASA LightT",
                        "Asa Light.jpg",
                        "",
                        "Apartment",
                        "NaN",
                        "Bùi Viện",
                        "P.Bến Nghé",
                        "Quận 1",
                        "71000",
                        "USD",
                        "150",
                        "3",
                        "3",
                        "1",
                        "lythihuyenchau@gmail.com",
                        "Đã duyệt",
                        "Done",
                        "Agency"});
#line 27
 testRunner.Then("the project details should show", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
