//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserManagement
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> SecretQuestion_ID { get; set; }
        public string Question_String { get; set; }
        public string Answer { get; set; }
    }
}
