//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_District_Street
    {
        public int District_ID { get; set; }
        public string DistrictName { get; set; }
        public int Street_ID { get; set; }
        public string StreetName { get; set; }
    }
}
