//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_project_from_index
    {
        public int ID { get; set; }
        public string PropertyName { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> Price { get; set; }
        public string Area { get; set; }
        public Nullable<int> BedRoom { get; set; }
        public Nullable<int> BathRoom { get; set; }
        public string DistrictName { get; set; }
        public string WardName { get; set; }
        public string StreetName { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public Nullable<int> PackingPlace { get; set; }
        public Nullable<int> Street_ID { get; set; }
        public Nullable<int> Ward_ID { get; set; }
        public Nullable<int> District_ID { get; set; }
    }
}
